# Generated by Django 3.2 on 2021-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(unique=True, upload_to='')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
