# Generated by Django 3.2 on 2021-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
